# coding: utf-8

"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FoodAttribute(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'sequence_number': 'int',
        'value': 'str',
        'food_attribute_type': 'FoodAttributeFoodAttributeType'
    }

    attribute_map = {
        'id': 'id',
        'sequence_number': 'sequenceNumber',
        'value': 'value',
        'food_attribute_type': 'FoodAttributeType'
    }

    def __init__(self, id=None, sequence_number=None, value=None, food_attribute_type=None):  # noqa: E501
        """FoodAttribute - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._sequence_number = None
        self._value = None
        self._food_attribute_type = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if sequence_number is not None:
            self.sequence_number = sequence_number
        if value is not None:
            self.value = value
        if food_attribute_type is not None:
            self.food_attribute_type = food_attribute_type

    @property
    def id(self):
        """Gets the id of this FoodAttribute.  # noqa: E501


        :return: The id of this FoodAttribute.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FoodAttribute.


        :param id: The id of this FoodAttribute.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def sequence_number(self):
        """Gets the sequence_number of this FoodAttribute.  # noqa: E501


        :return: The sequence_number of this FoodAttribute.  # noqa: E501
        :rtype: int
        """
        return self._sequence_number

    @sequence_number.setter
    def sequence_number(self, sequence_number):
        """Sets the sequence_number of this FoodAttribute.


        :param sequence_number: The sequence_number of this FoodAttribute.  # noqa: E501
        :type: int
        """

        self._sequence_number = sequence_number

    @property
    def value(self):
        """Gets the value of this FoodAttribute.  # noqa: E501


        :return: The value of this FoodAttribute.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this FoodAttribute.


        :param value: The value of this FoodAttribute.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def food_attribute_type(self):
        """Gets the food_attribute_type of this FoodAttribute.  # noqa: E501


        :return: The food_attribute_type of this FoodAttribute.  # noqa: E501
        :rtype: FoodAttributeFoodAttributeType
        """
        return self._food_attribute_type

    @food_attribute_type.setter
    def food_attribute_type(self, food_attribute_type):
        """Sets the food_attribute_type of this FoodAttribute.


        :param food_attribute_type: The food_attribute_type of this FoodAttribute.  # noqa: E501
        :type: FoodAttributeFoodAttributeType
        """

        self._food_attribute_type = food_attribute_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FoodAttribute, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FoodAttribute):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
