# coding: utf-8

"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WweiaFoodCategory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'wweia_food_category_code': 'int',
        'wweia_food_category_description': 'str'
    }

    attribute_map = {
        'wweia_food_category_code': 'wweiaFoodCategoryCode',
        'wweia_food_category_description': 'wweiaFoodCategoryDescription'
    }

    def __init__(self, wweia_food_category_code=None, wweia_food_category_description=None):  # noqa: E501
        """WweiaFoodCategory - a model defined in Swagger"""  # noqa: E501
        self._wweia_food_category_code = None
        self._wweia_food_category_description = None
        self.discriminator = None
        if wweia_food_category_code is not None:
            self.wweia_food_category_code = wweia_food_category_code
        if wweia_food_category_description is not None:
            self.wweia_food_category_description = wweia_food_category_description

    @property
    def wweia_food_category_code(self):
        """Gets the wweia_food_category_code of this WweiaFoodCategory.  # noqa: E501


        :return: The wweia_food_category_code of this WweiaFoodCategory.  # noqa: E501
        :rtype: int
        """
        return self._wweia_food_category_code

    @wweia_food_category_code.setter
    def wweia_food_category_code(self, wweia_food_category_code):
        """Sets the wweia_food_category_code of this WweiaFoodCategory.


        :param wweia_food_category_code: The wweia_food_category_code of this WweiaFoodCategory.  # noqa: E501
        :type: int
        """

        self._wweia_food_category_code = wweia_food_category_code

    @property
    def wweia_food_category_description(self):
        """Gets the wweia_food_category_description of this WweiaFoodCategory.  # noqa: E501


        :return: The wweia_food_category_description of this WweiaFoodCategory.  # noqa: E501
        :rtype: str
        """
        return self._wweia_food_category_description

    @wweia_food_category_description.setter
    def wweia_food_category_description(self, wweia_food_category_description):
        """Sets the wweia_food_category_description of this WweiaFoodCategory.


        :param wweia_food_category_description: The wweia_food_category_description of this WweiaFoodCategory.  # noqa: E501
        :type: str
        """

        self._wweia_food_category_description = wweia_food_category_description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WweiaFoodCategory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WweiaFoodCategory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
